### ISSUE TITLE
CUDA core dump

### ISSUE THREAD

**Issue by taewookim** [smivv/pytorch-chexnet#3]
Settings:

python 3.6.3
pytorch 0.3.0.post4
django 2.0.1
cuda

> nvcc: NVIDIA (R) Cuda compiler driver
> Copyright (c) 2005-2016 NVIDIA Corporation
> Built on Tue_Jan_10_13:22:03_CST_2017
> Cuda compilation tools, release 8.0, V8.0.61

Getting this insane error:

> python manage.py runserver 0:8000
> Performing system checks...
> 
> System check identified no issues (0 silenced).
> 
> You have 14 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
> Run 'python manage.py migrate' to apply them.
> 
> January 31, 2018 - 04:06:50
> Django version 2.0.1, using settings 'chexnetsite.settings'
> Starting development server at http://0:8000/
> Quit the server with CONTROL-C.
> [31/Jan/2018 04:07:07] "GET / HTTP/1.1" 200 404
> THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1512386481460/work/torch/lib/THC/THCGeneral.c line=70 error=30 : unknown error
> Internal Server Error: /handle
> Traceback (most recent call last):
>   File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
>     response = get_response(request)
>   File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
>     response = self.process_exception_by_middleware(e, request)
>   File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
>     response = wrapped_callback(request, *callback_args, **callback_kwargs)
>   File "/home/ubuntu/chexnet/pytorch-chexnet/chexnetsite/views.py", line 26, in handle
>     pred = process([path])
>   File "/home/ubuntu/chexnet/pytorch-chexnet/classes/model.py", line 57, in process
>     model = DenseNet121(N_CLASSES).cuda()
>   File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 216, in cuda
>     return self._apply(lambda t: t.cuda(device))
>   File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 146, in _apply
>     module._apply(fn)
>   File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 146, in _apply
>     module._apply(fn)
>   File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 146, in _apply
>     module._apply(fn)
>   File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 152, in _apply
>     param.data = fn(param.data)
>   File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 216, in <lambda>
>     return self._apply(lambda t: t.cuda(device))
>   File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/_utils.py", line 69, in _cuda
>     return new_type(self.size()).copy_(self, async)
>   File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/cuda/__init__.py", line 358, in _lazy_new
>     _lazy_init()
>   File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/cuda/__init__.py", line 121, in _lazy_init
>     torch._C._cuda_init()
> RuntimeError: cuda runtime error (30) : unknown error at /opt/conda/conda-bld/pytorch_1512386481460/work/torch/lib/THC/THCGeneral.c:70
> [31/Jan/2018 04:07:18] "POST /handle HTTP/1.1" 500 146635
> Segmentation fault (core dumped)

**Comment by taewookim** [comment]
Note.. this is after I upload a [CXR image](https://www.med-ed.virginia.edu/courses/rad/cxr/web%20images/solitary%20nodule%20LUL%20PA.jpg)

**Comment by taewookim** [comment]
If anyone has this issue, apparently updating Ubuntu seems to damage the nvidia drivers: https://discuss.pytorch.org/t/resolved-cuda-runtime-error-30/1116

Reinstalling driver & rebooting seems to help
